### ISSUE TITLE
compute rusticl option

### ISSUE THREAD

**Issue by walterav1984** [illwieckz/illwieckz#1]
Since you did a lot of work summing up the current AMDGPU OpenCl situation on linux with I-love-compute, I noticed you referenced MESA Clover but not (yet) MESA `rusticl`? It mentions 'image' support and v3 compliance, maybe you are already familiar with it than ignore this issue. Nevermind, just saw your post in that repo 3 days ago's... 

https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/15439
https://www.phoronix.com/scan.php?page=news_item&px=Mesa-OpenCL-3.0-CTS-Passes

**Comment by illwieckz** [comment]
Hi @walterav1984 thank you for the notice! Yes I'm already tracking it. 😁️ I just updated the [I love compute page](https://gitlab.com/illwieckz/i-love-compute) to mention it. I was busy those days writing a [script to build it](https://gitlab.com/illwieckz/i-love-compute/-/blob/master/scripts/user-rusticl) and test it. 😉️

I also updated the page about some other projects I found, like [mesa3d-comp-bridge](https://github.com/matszpk/mesa3d-comp-bridge) that was plugging Mesa Clover over AMD proprietary OpenCL compiler 🤔️, and [CLara](https://gitlab.com/illwieckz/clara) which was a project to expose OpenCL devices over the network (!)… it would be awesome to find some new contributors to CLara! 🤯️

Don't hesitate to submit on the [I love compute](https://gitlab.com/illwieckz/i-love-compute/-/issues) issue tracker other findings you may believe it would be worth referencing! 👍️

**Note:** I'm closing this ticket to reduce my list of opened tickets but feel free to answer there if you need to. 😉️
